"""Build a shippable Windows package of ECM Tracker with Nuitka.

The application is COMPILED into a standalone binary; the ``bundled_plugins/`` folder is
shipped as plain Python *next to* the exe, so clients can read the SDK and write
or edit their own plugins (which import the compiled ``app`` package at runtime).

Produces, under ``dist/``:
  * ECMTracker-<version>-win64.zip   — unzip and run ECMTracker.exe
  * ECMTracker-<version>-setup.exe   — per-user installer (only if Inno Setup is present)

Usage (from repo root) — bump ``version`` in pyproject.toml first to stamp a release:

    uv run python build.py

First run downloads Nuitka's MinGW64 toolchain and takes several minutes; it is a
release-time cost only and never touches the normal `uv run python -m app.main` dev loop.
"""
from __future__ import annotations

import shutil
import subprocess
import sys
import tempfile
import uuid
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent
# Nuitka's compile scratch MUST live outside the Dropbox-synced tree. Dropbox locks
# intermediate files mid-build to sync them, which makes Nuitka's delete-after-use
# race fail with "WinError 32 ... used by another process". Only the final artifacts
# (dist/) stay in the repo. Same reason .venv is never synced (see CLAUDE.md).
BUILD_DIR = Path(tempfile.gettempdir()) / ("ecmtracker-build-" + uuid.uuid4().hex)
DIST_DIR = ROOT / "dist"
ENTRY = ROOT / "run.py"
ICON = ROOT / "assets" / "app_icon.ico"

APP_NAME = "ECMTracker"       # exe + folder name (no spaces, simplest for zip/installer)
DISPLAY_NAME = "ECM Tracker"  # human-facing name (window/installer/metadata)
PUBLISHER = "Senecell"

# Folders Nuitka can't reach by following imports from the compiled core and that
# we therefore force in. scipy + matplotlib are imported *only* by loose plugins;
# cv2's data is included defensively (the core imports cv2, so code is followed).
_DONT_COPY = shutil.ignore_patterns("__pycache__", "*.pyc", "*.tmp.*")


def _version() -> str:
    data = tomllib.loads((ROOT / "pyproject.toml").read_text("utf-8"))
    return data["project"]["version"]


def _nuitka_cmd(version: str) -> list[str]:
    return [
        sys.executable, "-m", "nuitka",
        "--mode=standalone",
        "--windows-console-mode=disable",          # GUI app: no console window
        "--enable-plugin=pyside6",
        f"--windows-icon-from-ico={ICON}",
        "--include-package=app",                    # whole app package ...
        "--include-package-data=app",               # ... plus its runtime-loaded SVG icons
        "--include-package=scipy",                  # plugin-only: core never imports it
        "--include-package=matplotlib",             # plugin-only: core never imports it (data auto-bundled)
        "--include-package-data=cv2",               # ship opencv data defensively
        f"--company-name={PUBLISHER}",
        f"--product-name={DISPLAY_NAME}",
        f"--file-description={DISPLAY_NAME}",
        f"--file-version={version}",
        f"--product-version={version}",
        "--assume-yes-for-downloads",               # fetch MinGW toolchain non-interactively
        "--remove-output",                          # drop the .build intermediate dir
        f"--output-dir={BUILD_DIR}",
        f"--output-filename={APP_NAME}.exe",
        str(ENTRY),
    ]


# Per-user install (no admin, plugins/ stays user-writable so clients can edit them).
# For an all-users install instead, set PrivilegesRequired=admin and
# DefaultDirName={{autopf}}\\{display}.
_ISS = """\
; Auto-generated by build.py — do not edit by hand.
[Setup]
AppName={display}
AppVersion={version}
AppPublisher={publisher}
DefaultDirName={{localappdata}}\\Programs\\{display}
DefaultGroupName={display}
PrivilegesRequired=lowest
OutputDir={outdir}
OutputBaseFilename={appname}-{version}-setup
SetupIconFile={icon}
Compression=lzma2
SolidCompression=yes
WizardStyle=modern

[Files]
Source: "{payload}\\*"; DestDir: "{{app}}"; Flags: recursesubdirs createallsubdirs

[Icons]
Name: "{{group}}\\{display}"; Filename: "{{app}}\\{appname}.exe"
Name: "{{group}}\\Uninstall {display}"; Filename: "{{uninstallexe}}"

[Run]
Filename: "{{app}}\\{appname}.exe"; Description: "Launch {display}"; Flags: nowait postinstall skipifsilent
"""


def _stage_payload() -> Path:
    """Rename Nuitka's run.dist -> build/ECMTracker and drop loose plugins/ inside it."""
    payload = BUILD_DIR / APP_NAME
    if payload.exists():
        shutil.rmtree(payload)
    (BUILD_DIR / "run.dist").rename(payload)
    shutil.copytree(ROOT / "plugins", payload / "bundled_plugins", ignore=_DONT_COPY)
    return payload


def _make_zip(payload: Path, version: str) -> Path:
    base = DIST_DIR / f"{APP_NAME}-{version}-win64"
    return Path(shutil.make_archive(str(base), "zip", root_dir=BUILD_DIR, base_dir=payload.name))


def _find_iscc() -> str | None:
    found = shutil.which("ISCC")
    if found:
        return found
    for base in (r"C:\Program Files (x86)\Inno Setup 6", r"C:\Program Files\Inno Setup 6"):
        cand = Path(base) / "ISCC.exe"
        if cand.exists():
            return str(cand)
    return None


def _make_installer(payload: Path, version: str) -> Path | None:
    iss_path = BUILD_DIR / "installer.iss"
    iss_path.write_text(
        _ISS.format(
            display=DISPLAY_NAME, version=version, publisher=PUBLISHER,
            outdir=DIST_DIR, appname=APP_NAME, icon=ICON, payload=payload,
        ),
        "utf-8",
    )
    iscc = _find_iscc()
    if iscc is None:
        print("  ! Inno Setup (ISCC.exe) not found — skipping installer.")
        print("    Install it from https://jrsoftware.org/isdl.php, then run:")
        print(f'      & "C:\\Program Files (x86)\\Inno Setup 6\\ISCC.exe" "{iss_path}"')
        return None
    subprocess.run([iscc, str(iss_path)], check=True)
    return DIST_DIR / f"{APP_NAME}-{version}-setup.exe"


def main() -> int:
    version = _version()
    print(f"Building {DISPLAY_NAME} {version} ...")
    if BUILD_DIR.exists():
        raise RuntimeError("Build scratch directory unexpectedly exists")
    BUILD_DIR.mkdir()
    subprocess.run([sys.executable, "scripts/build_sdk.py"], check=True, cwd=ROOT)
    subprocess.run([sys.executable, "scripts/check.py"], check=True, cwd=ROOT)
    DIST_DIR.mkdir(exist_ok=True)

    subprocess.run(_nuitka_cmd(version), check=True, cwd=ROOT)

    payload = _stage_payload()
    print(f"  payload   -> {payload}")
    print(f"  zip       -> {_make_zip(payload, version)}")
    installer = _make_installer(payload, version)
    if installer is not None:
        print(f"  installer -> {installer}")
    print("Done.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
